/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    ErrorState: typeof import('./src/components/ui/ErrorState.vue')['default']
    LoadingState: typeof import('./src/components/ui/LoadingState.vue')['default']
    RocketCard: typeof import('./src/components/rockets/RocketCard.vue')['default']
    RocketDetail: typeof import('./src/components/rockets/RocketDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
